/* tslint:disable */
/* eslint-disable */
/**
 * live-dev-trends API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner
 */
export interface ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner {
  /**
   *
   * @type {string}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner
   */
  topic: string;
  /**
   *
   * @type {number}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner
   */
  eventCount: number;
  /**
   *
   * @type {number}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner
   */
  uniqueRepos: number;
  /**
   *
   * @type {number}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner
   */
  uniqueUsers: number;
}

/**
 * Check if a given object implements the ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner interface.
 */
export function instanceOfConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner(
  value: object,
): value is ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner {
  if (!("topic" in value) || value["topic"] === undefined) return false;
  if (!("eventCount" in value) || value["eventCount"] === undefined)
    return false;
  if (!("uniqueRepos" in value) || value["uniqueRepos"] === undefined)
    return false;
  if (!("uniqueUsers" in value) || value["uniqueUsers"] === undefined)
    return false;
  return true;
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerFromJSON(
  json: any,
): ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner {
  return ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerFromJSONTyped(
    json,
    false,
  );
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner {
  if (json == null) {
    return json;
  }
  return {
    topic: json["topic"],
    eventCount: json["eventCount"],
    uniqueRepos: json["uniqueRepos"],
    uniqueUsers: json["uniqueUsers"],
  };
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerToJSON(
  json: any,
): ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner {
  return ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerToJSONTyped(
    json,
    false,
  );
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerToJSONTyped(
  value?: ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    topic: value["topic"],
    eventCount: value["eventCount"],
    uniqueRepos: value["uniqueRepos"],
    uniqueUsers: value["uniqueUsers"],
  };
}
