# This file was auto-generated by the framework. You can add data models or change the existing ones

from moose_lib import Key
from moose_lib.dmv2 import IngestPipeline, DataModelConfigV2, StreamConfig
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field

class Foo(BaseModel):
    primary_key: Key[str]
    timestamp: float
    optional_text: Optional[str]

class Bar(BaseModel):
    primary_key: Key[str]
    utc_timestamp: datetime
    has_text: bool
    text_length: int

fooModel = IngestPipeline[Foo]("foo", DataModelConfigV2(
    ingest=True,
    stream=True,
    table=False
))

barModel = IngestPipeline[Bar]("bar", DataModelConfigV2(
    ingest=False,
    stream=True,
    table=True
))
