// This file was auto-generated by the framework. You can add data models or change the existing ones
import { IngestPipeline, Key } from "@514labs/moose-lib";

export interface Foo {
  primaryKey: Key<string>;
  timestamp: number;
  optionalText?: string;
}

export interface Bar {
  primaryKey: Key<string>;
  utcTimestamp: Date;
  hasText: boolean;
  textLength: number;
}

export const FooPipeline = new IngestPipeline<Foo>("Foo", {
  table: false,
  stream: true,
  ingest: true,
});

export const BarPipeline = new IngestPipeline<Bar>("Bar", {
  table: true,
  stream: true,
  ingest: false,
});
