/* tslint:disable */
/* eslint-disable */
/**
 * live-dev-trends API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner } from "./ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner";
import {
  ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerFromJSON,
  ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerFromJSONTyped,
  ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerToJSON,
  ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerToJSONTyped,
} from "./ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner";

/**
 *
 * @export
 * @interface ConsumptionTopicTimeseriesGet200ResponseInner
 */
export interface ConsumptionTopicTimeseriesGet200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInner
   */
  time: string;
  /**
   *
   * @type {Array<ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner>}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInner
   */
  topicStats: Array<ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInner>;
}

/**
 * Check if a given object implements the ConsumptionTopicTimeseriesGet200ResponseInner interface.
 */
export function instanceOfConsumptionTopicTimeseriesGet200ResponseInner(
  value: object,
): value is ConsumptionTopicTimeseriesGet200ResponseInner {
  if (!("time" in value) || value["time"] === undefined) return false;
  if (!("topicStats" in value) || value["topicStats"] === undefined)
    return false;
  return true;
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerFromJSON(
  json: any,
): ConsumptionTopicTimeseriesGet200ResponseInner {
  return ConsumptionTopicTimeseriesGet200ResponseInnerFromJSONTyped(
    json,
    false,
  );
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConsumptionTopicTimeseriesGet200ResponseInner {
  if (json == null) {
    return json;
  }
  return {
    time: json["time"],
    topicStats: (json["topicStats"] as Array<any>).map(
      ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerFromJSON,
    ),
  };
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerToJSON(
  json: any,
): ConsumptionTopicTimeseriesGet200ResponseInner {
  return ConsumptionTopicTimeseriesGet200ResponseInnerToJSONTyped(json, false);
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerToJSONTyped(
  value?: ConsumptionTopicTimeseriesGet200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    time: value["time"],
    topicStats: (value["topicStats"] as Array<any>).map(
      ConsumptionTopicTimeseriesGet200ResponseInnerTopicStatsInnerToJSON,
    ),
  };
}
