

# This file was auto-generated by the framework. You can add data models or change the existing ones
from app.ingest import models, transforms
import app.apis.bar as bar_api
import app.views.bar_aggregated as bar_view




