/* tslint:disable */
/* eslint-disable */
/**
 * ts API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TopicStats } from "./TopicStats";
import {
  TopicStatsFromJSON,
  TopicStatsFromJSONTyped,
  TopicStatsToJSON,
  TopicStatsToJSONTyped,
} from "./TopicStats";

/**
 *
 * @export
 * @interface ResponseBody
 */
export interface ResponseBody {
  /**
   *
   * @type {string}
   * @memberof ResponseBody
   */
  time: string;
  /**
   *
   * @type {Array<TopicStats>}
   * @memberof ResponseBody
   */
  topicStats: Array<TopicStats>;
}

/**
 * Check if a given object implements the ResponseBody interface.
 */
export function instanceOfResponseBody(value: object): value is ResponseBody {
  if (!("time" in value) || value["time"] === undefined) return false;
  if (!("topicStats" in value) || value["topicStats"] === undefined)
    return false;
  return true;
}

export function ResponseBodyFromJSON(json: any): ResponseBody {
  return ResponseBodyFromJSONTyped(json, false);
}

export function ResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponseBody {
  if (json == null) {
    return json;
  }
  return {
    time: json["time"],
    topicStats: (json["topicStats"] as Array<any>).map(TopicStatsFromJSON),
  };
}

export function ResponseBodyToJSON(json: any): ResponseBody {
  return ResponseBodyToJSONTyped(json, false);
}

export function ResponseBodyToJSONTyped(
  value?: ResponseBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    time: value["time"],
    topicStats: (value["topicStats"] as Array<any>).map(TopicStatsToJSON),
  };
}
