/* tslint:disable */
/* eslint-disable */
/**
 * ts API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TopicStats
 */
export interface TopicStats {
  /**
   *
   * @type {string}
   * @memberof TopicStats
   */
  topic: string;
  /**
   *
   * @type {number}
   * @memberof TopicStats
   */
  uniqueUsers: number;
  /**
   *
   * @type {number}
   * @memberof TopicStats
   */
  eventCount: number;
  /**
   *
   * @type {number}
   * @memberof TopicStats
   */
  uniqueRepos: number;
}

/**
 * Check if a given object implements the TopicStats interface.
 */
export function instanceOfTopicStats(value: object): value is TopicStats {
  if (!("topic" in value) || value["topic"] === undefined) return false;
  if (!("uniqueUsers" in value) || value["uniqueUsers"] === undefined)
    return false;
  if (!("eventCount" in value) || value["eventCount"] === undefined)
    return false;
  if (!("uniqueRepos" in value) || value["uniqueRepos"] === undefined)
    return false;
  return true;
}

export function TopicStatsFromJSON(json: any): TopicStats {
  return TopicStatsFromJSONTyped(json, false);
}

export function TopicStatsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TopicStats {
  if (json == null) {
    return json;
  }
  return {
    topic: json["topic"],
    uniqueUsers: json["uniqueUsers"],
    eventCount: json["eventCount"],
    uniqueRepos: json["uniqueRepos"],
  };
}

export function TopicStatsToJSON(json: any): TopicStats {
  return TopicStatsToJSONTyped(json, false);
}

export function TopicStatsToJSONTyped(
  value?: TopicStats | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    topic: value["topic"],
    uniqueUsers: value["uniqueUsers"],
    eventCount: value["eventCount"],
    uniqueRepos: value["uniqueRepos"],
  };
}
