// This file was auto-generated by the framework. You can add data models or change the existing ones
type Key<T extends string | number> = T;

export interface PageViewRaw {
  eventId: Key<string>;
  timestamp: Date;
  session_id: string;
  user_agent: string;
  locale: string;
  location: string;
  href: string;
  pathname: string;
  referrer: string;
}

export interface PageViewProcessed {
  eventId: Key<string>;
  timestamp: Date;
  session_id: string;
  locale: string;
  location: string;
  href: string;
  hostname: string;
  pathname: string;
  referrer: string;
  device_manufacturer: string;
  browser_type: string;
  browser_version: string;
  os: string;
  os_version: string;
}

export interface MooseActivityAugmented {
  id: Key<string>;
  project: string;
  activityType: string;
  sequenceId: string;
  timestamp: Date;
  cliVersion: string;
  isMooseDeveloper?: boolean;
  machineId: string;
  hashedIp?: string;
  cityName?: string;
  countryCode?: string;
  companyName?: string;
  companyType?: string;
  companyDomain?: string;
}
