// This file was auto-generated by the framework. You can add data models or change the existing ones
import { Key } from "@514labs/moose-lib";

export interface PageViewRaw {
  eventId: Key<string>;
  timestamp: Date;
  session_id: string;
  user_agent: string;
  locale: string;
  location: string;
  href: string;
  pathname: string;
  referrer: string;
}

export interface PageViewProcessed extends PageViewRaw {
  hostname: string;
  device_vendor: string;
  device_type: string;
  device_model: string;
  browser_name: string;
  browser_version: string;
  os_name: string;
  os_version: string;
}
