import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex flex-row w-screen px-4">
          <header className="flex text-lg">
            <a className="py-4" href={"/"}>
              <span className="py-4">moosejs</span>
            </a>
            <span className="flex-grow" />
          </header>
          <span className="flex-grow" />
          <div className="py-3">
            <a className="py-4" href={"/insights"}>
              <span className="py-4">Insights</span>
            </a>
          </div>
          <div className="ml-3">
            <div className="py-3 flex flex-row align-middle justify-center "></div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
