blank_issues_enabled: false
contact_links:
  - name: MooseJS Community
    url: https://join.slack.com/t/moose-community/shared_invite/zt-2fjh5n3wz-cnOmM9Xe9DYAgQrNu8xKxg
    about: Please ask and answer questions here.
