// This file was auto-generated by the framework. You can add data models or change the existing ones

import { Key, IngestPipeline } from "@514labs/moose-lib";

export interface UserActivity {
  eventId: Key<string>;
  timestamp: string;
  userId: string;
  activity: string;
}

export interface ParsedActivity {
  eventId: Key<string>;
  timestamp: Date;
  userId: string;
  activity: string;
}
// DMV2 Pipeline for UserActivity
export const UserActivityPipeline = new IngestPipeline<UserActivity>(
  "UserActivity",
  {
    table: {
      orderByFields: ["eventId", "timestamp"],
      engine: ClickHouseEngines.ReplacingMergeTree,
    },
    stream: true,
    ingestApi: true, // POST /ingest/UserActivity
  },
);

// DMV2 Pipeline for ParsedActivity (derived from UserActivity via streaming function)
export const ParsedActivityPipeline = new IngestPipeline<ParsedActivity>(
  "ParsedActivity",
  {
    table: {
      orderByFields: ["eventId", "timestamp"],
      engine: ClickHouseEngines.ReplacingMergeTree,
    },
    stream: true,
    ingestApi: false, // No direct ingest API; populated by streaming function
  },
);
