//! Template for generating data models
//!
//! We only generate a static base model for now. We'll add dynamic templates with tinytemplates in the future

pub static BASE_MODEL_TEMPLATE: &str = r#"
// This file was auto-generated by the framework. You can add data models or change the existing ones

model UserActivity {
    eventId   String @id
    timestamp DateTime
    userId    String
    activity  String
}

model ProcessedActivity {
    id        String @id
    userId    String
    activity  String
}

"#;

pub static BASE_FLOW_TEMPLATE: &str = r#"
// This file was auto-generated by the framework.
// TODO: Add more context about flows and how to use them.

import { ProcessedActivity } from "../../../../.moose/{{project_name}}-sdk/ProcessedActivity.ts";
import { UserActivity } from "../../../../.moose/{{project_name}}-sdk/UserActivity.ts";

export default function run(event: UserActivity): ProcessedActivity {
    return {
        id: event.eventId,
        userId: `puid_${event.userId}`,
        activity: event.activity,
    }
}

"#;
