/* tslint:disable */
/* eslint-disable */
/**
 * live-dev-trends API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ConsumptionTopicTimeseriesGet200ResponseInner
 */
export interface ConsumptionTopicTimeseriesGet200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInner
   */
  minute?: string;
  /**
   *
   * @type {string}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInner
   */
  day?: string;
  /**
   *
   * @type {string}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInner
   */
  week?: string;
  /**
   *
   * @type {string}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInner
   */
  topic: string;
  /**
   *
   * @type {number}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInner
   */
  totalEvents: number;
  /**
   *
   * @type {number}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInner
   */
  uniqueReposCount: number;
  /**
   *
   * @type {number}
   * @memberof ConsumptionTopicTimeseriesGet200ResponseInner
   */
  uniqueUsersCount: number;
}

/**
 * Check if a given object implements the ConsumptionTopicTimeseriesGet200ResponseInner interface.
 */
export function instanceOfConsumptionTopicTimeseriesGet200ResponseInner(
  value: object,
): value is ConsumptionTopicTimeseriesGet200ResponseInner {
  if (!("topic" in value) || value["topic"] === undefined) return false;
  if (!("totalEvents" in value) || value["totalEvents"] === undefined)
    return false;
  if (!("uniqueReposCount" in value) || value["uniqueReposCount"] === undefined)
    return false;
  if (!("uniqueUsersCount" in value) || value["uniqueUsersCount"] === undefined)
    return false;
  return true;
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerFromJSON(
  json: any,
): ConsumptionTopicTimeseriesGet200ResponseInner {
  return ConsumptionTopicTimeseriesGet200ResponseInnerFromJSONTyped(
    json,
    false,
  );
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConsumptionTopicTimeseriesGet200ResponseInner {
  if (json == null) {
    return json;
  }
  return {
    minute: json["minute"] == null ? undefined : json["minute"],
    day: json["day"] == null ? undefined : json["day"],
    week: json["week"] == null ? undefined : json["week"],
    topic: json["topic"],
    totalEvents: json["totalEvents"],
    uniqueReposCount: json["uniqueReposCount"],
    uniqueUsersCount: json["uniqueUsersCount"],
  };
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerToJSON(
  json: any,
): ConsumptionTopicTimeseriesGet200ResponseInner {
  return ConsumptionTopicTimeseriesGet200ResponseInnerToJSONTyped(json, false);
}

export function ConsumptionTopicTimeseriesGet200ResponseInnerToJSONTyped(
  value?: ConsumptionTopicTimeseriesGet200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    minute: value["minute"],
    day: value["day"],
    week: value["week"],
    topic: value["topic"],
    totalEvents: value["totalEvents"],
    uniqueReposCount: value["uniqueReposCount"],
    uniqueUsersCount: value["uniqueUsersCount"],
  };
}
