/* tslint:disable */
/* eslint-disable */
/**
 * live-dev-trends API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WatchEventWithRepo
 */
export interface WatchEventWithRepo {
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoUrl: string;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  createdAt: string;
  /**
   *
   * @type {number}
   * @memberof WatchEventWithRepo
   */
  repoStars?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof WatchEventWithRepo
   */
  repoTopics?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoOrgUrl?: string;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  actorAvatarUrl: string;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoOwnerLogin?: string;
  /**
   *
   * @type {number}
   * @memberof WatchEventWithRepo
   */
  repoOrgId?: number;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoOrgLogin?: string;
  /**
   *
   * @type {number}
   * @memberof WatchEventWithRepo
   */
  repoWatchers?: number;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoCreatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoOwnerType?: string;
  /**
   *
   * @type {number}
   * @memberof WatchEventWithRepo
   */
  repoForks?: number;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  eventId: string;
  /**
   *
   * @type {number}
   * @memberof WatchEventWithRepo
   */
  repoOpenIssues?: number;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoLanguage?: string;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  actorLogin: string;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoHomepage?: string;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  actorUrl: string;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoName: string;
  /**
   *
   * @type {number}
   * @memberof WatchEventWithRepo
   */
  repoOwnerId?: number;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoOwnerAvatarUrl?: string;
  /**
   *
   * @type {number}
   * @memberof WatchEventWithRepo
   */
  repoId: number;
  /**
   *
   * @type {number}
   * @memberof WatchEventWithRepo
   */
  actorId: number;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoOwnerUrl?: string;
  /**
   *
   * @type {string}
   * @memberof WatchEventWithRepo
   */
  repoDescription?: string;
}

/**
 * Check if a given object implements the WatchEventWithRepo interface.
 */
export function instanceOfWatchEventWithRepo(
  value: object,
): value is WatchEventWithRepo {
  if (!("repoUrl" in value) || value["repoUrl"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("actorAvatarUrl" in value) || value["actorAvatarUrl"] === undefined)
    return false;
  if (!("eventId" in value) || value["eventId"] === undefined) return false;
  if (!("actorLogin" in value) || value["actorLogin"] === undefined)
    return false;
  if (!("actorUrl" in value) || value["actorUrl"] === undefined) return false;
  if (!("repoName" in value) || value["repoName"] === undefined) return false;
  if (!("repoId" in value) || value["repoId"] === undefined) return false;
  if (!("actorId" in value) || value["actorId"] === undefined) return false;
  return true;
}

export function WatchEventWithRepoFromJSON(json: any): WatchEventWithRepo {
  return WatchEventWithRepoFromJSONTyped(json, false);
}

export function WatchEventWithRepoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WatchEventWithRepo {
  if (json == null) {
    return json;
  }
  return {
    repoUrl: json["repoUrl"],
    createdAt: json["createdAt"],
    repoStars: json["repoStars"] == null ? undefined : json["repoStars"],
    repoTopics: json["repoTopics"] == null ? undefined : json["repoTopics"],
    repoOrgUrl: json["repoOrgUrl"] == null ? undefined : json["repoOrgUrl"],
    actorAvatarUrl: json["actorAvatarUrl"],
    repoOwnerLogin:
      json["repoOwnerLogin"] == null ? undefined : json["repoOwnerLogin"],
    repoOrgId: json["repoOrgId"] == null ? undefined : json["repoOrgId"],
    repoOrgLogin:
      json["repoOrgLogin"] == null ? undefined : json["repoOrgLogin"],
    repoWatchers:
      json["repoWatchers"] == null ? undefined : json["repoWatchers"],
    repoCreatedAt:
      json["repoCreatedAt"] == null ? undefined : json["repoCreatedAt"],
    repoOwnerType:
      json["repoOwnerType"] == null ? undefined : json["repoOwnerType"],
    repoForks: json["repoForks"] == null ? undefined : json["repoForks"],
    eventId: json["eventId"],
    repoOpenIssues:
      json["repoOpenIssues"] == null ? undefined : json["repoOpenIssues"],
    repoLanguage:
      json["repoLanguage"] == null ? undefined : json["repoLanguage"],
    actorLogin: json["actorLogin"],
    repoHomepage:
      json["repoHomepage"] == null ? undefined : json["repoHomepage"],
    actorUrl: json["actorUrl"],
    repoName: json["repoName"],
    repoOwnerId: json["repoOwnerId"] == null ? undefined : json["repoOwnerId"],
    repoOwnerAvatarUrl:
      json["repoOwnerAvatarUrl"] == null
        ? undefined
        : json["repoOwnerAvatarUrl"],
    repoId: json["repoId"],
    actorId: json["actorId"],
    repoOwnerUrl:
      json["repoOwnerUrl"] == null ? undefined : json["repoOwnerUrl"],
    repoDescription:
      json["repoDescription"] == null ? undefined : json["repoDescription"],
  };
}

export function WatchEventWithRepoToJSON(json: any): WatchEventWithRepo {
  return WatchEventWithRepoToJSONTyped(json, false);
}

export function WatchEventWithRepoToJSONTyped(
  value?: WatchEventWithRepo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    repoUrl: value["repoUrl"],
    createdAt: value["createdAt"],
    repoStars: value["repoStars"],
    repoTopics: value["repoTopics"],
    repoOrgUrl: value["repoOrgUrl"],
    actorAvatarUrl: value["actorAvatarUrl"],
    repoOwnerLogin: value["repoOwnerLogin"],
    repoOrgId: value["repoOrgId"],
    repoOrgLogin: value["repoOrgLogin"],
    repoWatchers: value["repoWatchers"],
    repoCreatedAt: value["repoCreatedAt"],
    repoOwnerType: value["repoOwnerType"],
    repoForks: value["repoForks"],
    eventId: value["eventId"],
    repoOpenIssues: value["repoOpenIssues"],
    repoLanguage: value["repoLanguage"],
    actorLogin: value["actorLogin"],
    repoHomepage: value["repoHomepage"],
    actorUrl: value["actorUrl"],
    repoName: value["repoName"],
    repoOwnerId: value["repoOwnerId"],
    repoOwnerAvatarUrl: value["repoOwnerAvatarUrl"],
    repoId: value["repoId"],
    actorId: value["actorId"],
    repoOwnerUrl: value["repoOwnerUrl"],
    repoDescription: value["repoDescription"],
  };
}
