// ==================================================================================================
// |      WARNING: This file is generated by the framework. Do NOT modify this file directly.        |
// | This file will be removed in future releases that will use typescript as a modeling language.   |
// ==================================================================================================

export interface MooseActivity {
  id: string;
  project: string;
  activityType: string;
  sequenceId: string;
  timestamp: Date;
  cliVersion: string;
  isMooseDeveloper?: boolean;
  machineId: string;
}
