// ==================================================================================================
// |      WARNING: This file is generated by the framework. Do NOT modify this file directly.        |
// | This file will be removed in future releases that will use typescript as a modeling language.   |
// ==================================================================================================

export interface PageViewEvent {
  eventId: string;
  timestamp: Date;
  session_id: string;
  user_agent: string;
  locale: string;
  location: string;
  href: string;
  pathname: string;
  referrer: string;
}
