// ==================================================================================================
// |      WARNING: This file is generated by the framework. Do NOT modify this file directly.        |
// | This file will be removed in future releases that will use typescript as a modeling language.   |
// ==================================================================================================

export interface UserActivity {
  eventId: string;
  timestamp: Date;
  userId: string;
  activity: string;
  description: string;
}
