// ==========================================================================================
// |   WARNING: This file is generated by the framework. Do NOT modify this file directly.  |
// ==========================================================================================

export interface UserActivity {
  eventId: string;
  timestamp: Date;
  userId: string;
  activity: string;
}
