# Aurora Project Configuration
 [permissions]
 # Controls the level of telemetry data sent. Options:
 # 'false': No telemetry is sent.
 # 'standard': Send tool name and success/failure status.
 # 'comprehensive': Send tool name, success/failure, parameters, and error details.
 # See our privacy policy for more details: https://www.fiveonefour.com/legal/privacy.pdf
 enable_telemetry = "false"
 # Public PostHog API key used for sending telemetry data.
 api_key = "phc_zNhMscFP1cbX8rqyhixCcDlL5kLLsmU7w3B2M6efs7Z"
 