import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import NextAuthProvider from "./next-auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moose Internal Logs",
  description: "Logs generated by moose applications",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <Provider>
          <body className={inter.className}>{children}</body>
        </Provider>
      </NextAuthProvider>
    </html>
  );
}
