# This file was auto-generated by the framework. You can add data models or change the existing ones

from moose_lib import Key, IngestPipeline, IngestPipelineConfig
from datetime import datetime
from typing import Optional
from pydantic import BaseModel

class Foo(BaseModel):
    primary_key: Key[str]
    timestamp: float
    optional_text: Optional[str]

class Bar(BaseModel):
    primary_key: Key[str]
    utc_timestamp: datetime
    has_text: bool
    text_length: int

fooModel = IngestPipeline[Foo]("Foo", IngestPipelineConfig(
    ingest=True,
    stream=True,
    table=False
))

barModel = IngestPipeline[Bar]("Bar", IngestPipelineConfig(
    ingest=False,
    stream=True,
    table=True
))
